/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  lt: {
    language: "LT",
    switchLanguage: "English",
    brandSubtitle: "Miškininkystės analizė ir investavimas",
    navMap: "Žemėlapis",
    register: "Registruotis",
    login: "Prisijungti",
    logout: "Atsijungti",
    home: "Pagrindinis",
    goToMap: "Eiti į žemėlapį",
    choose: "Pasirinkti",
    cancelPlan: "Atšaukti planą",
    cancelPlanTitle: "Atšaukti aktyvų planą?",
    cancelPlanText: "Atšaukus planą prieiga prie žemėlapio bus sustabdyta, kol įsigysite kitą planą.",
    keepPlan: "Palikti planą",
    confirmCancelPlan: "Taip, atšaukti",
    currentPlanFirst: "Pirma atšaukite dabartinį planą",
    plan: "Planas",
    purchased: "Įsigyta",
    monthPeriod: "mėn.",
    loginTitle: "Prisijungimas",
    loginIntro: "Prisijunkite prie paskyros.",
    email: "El. paštas",
    password: "Slaptažodis",
    forgotPassword: "Pamiršote slaptažodį?",
    newAccount: "Nauja paskyra",
    invalidEmail: "Įveskite korektišką el. pašto adresą.",
    passwordRequired: "Įveskite slaptažodį.",
    loginSuccess: "Prisijungta sėkmingai.",
    accountCreated: "Paskyra sukurta sėkmingai.",
    registerTitle: "Registracija",
    registerIntro: "Sukurkite paskyrą ir pradėkite naudotis sistema.",
    name: "Vardas",
    firstName: "Vardas",
    lastName: "Pavardė",
    nameRequired: "Įveskite vardą.",
    firstNameRequired: "Įveskite vardą.",
    lastNameRequired: "Įveskite pavardę.",
    confirmPassword: "Patvirtinkite slaptažodį",
    createAccount: "Kurti paskyrą",
    alreadyHaveAccount: "Jau turite paskyrą?",
    passwordsDoNotMatch: "Slaptažodžiai nesutampa.",
    strongPassword: "Slaptažodis turi būti bent 8 simbolių, turėti didžiąją raidę, skaičių ir specialų simbolį.",
    heroChip: "Miškininkystės analizės ir investavimo platforma",
    heroSubtitle: "ForestForYou padeda vertinti Lietuvos miškų teritorijas pagal geoduomenis, infrastruktūrą, dirvožemio rodiklius ir aplinkosauginius ribojimus. Sistema apskaičiuoja investavimo indeksą ir leidžia naudotojui dinamiškai reguliuoti kriterijų svorius pagal savo prioritetus.",
    heroNote: "Interaktyvus žemėlapis ir erdvinė analizė leidžia greičiau atrasti perspektyvias teritorijas bei objektyviau palyginti skirtingas vietoves.",
    aboutProject: "Apie projektą",
    aboutProjectText: "ForestForYou yra sprendimų analizės platforma, orientuota į miškų teritorijų vertinimą ir investavimo konsultacijų procesą. Sistema sujungia GIS duomenų analizę, teritorijų vizualizaciją ir kriterijais paremtą vertinimo modelį, kuris padeda efektyviau priimti investicinius sprendimus. Platforma leidžia ne tik peržiūrėti geografinius duomenis, bet ir realiu laiku analizuoti teritorijų tinkamumą pagal naudotojo pasirinktus prioritetus.",
    choosePlan: "Pasirinkite planą",
    teamMembers: "Komandos nariai",
    mentor: "Mentorius",
    countyDayTitle: "Vienos dienos prieiga vienai apskričiai",
    countyDayDescription: "Trumpalaikė prieiga konkrečios apskrities duomenų peržiūrai ir investicinio potencialo įvertinimui.",
    lithuaniaDayTitle: "Vienos dienos prieiga visai Lietuvai",
    lithuaniaDayDescription: "Vienos dienos prieiga visos Lietuvos objektų peržiūrai, skirta greitam rinkos įvertinimui.",
    lithuaniaMonthTitle: "Mėnesio prenumerata visai Lietuvai",
    lithuaniaMonthDescription: "Prenumerata reguliariam darbui su visos Lietuvos duomenimis ir prioritetinėmis teritorijomis.",
    selectedPlan: "Pasirinktas planas",
    payment: "Mokėjimas",
    paymentSuccess: "Mokėjimas sėkmingas. Prieiga aktyvuota.",
    paymentRecordedError: "Mokėjimas atliktas, bet prieigos įrašyti nepavyko. Susisiekite su administracija.",
    paymentFailed: "Mokėjimas nepavyko. Patikrinkite duomenis ir bandykite dar kartą.",
    selectCounty: "Pasirinkite apskritį",
    loadingCounties: "Kraunamas apskričių sąrašas...",
    backHome: "Grįžti į pradinį puslapį",
    alreadyPurchasedText: "Jūs jau turite šį planą. Galite naudotis žemėlapiu.",
    activePlanBlocks: "Turite aktyvų kitą planą. Norėdami įsigyti šį, pirmiausia atšaukite dabartinį planą.",
    planCancelled: "Planas atšauktas. Dabar galite rinktis kitą planą.",
    mapAccessCheck: "Tikrinama prieiga...",
    mapLoading: "Kraunami žemėlapio duomenys...",
    status: "Būsena",
    dataReady: "Duomenys paruošti peržiūrai",
    dataLoadingShort: "Kraunama duomenų ištrauka...",
    objectCount: "Objektų kiekis",
    legend: "Legenda",
    excellent: "Labai tinkama",
    good: "Tinkama",
    average: "Vidutinė vertė",
    bad: "Ribota vertė",
    veryBad: "Netinkama",
    userWeights: "Naudotojo svoriai",
    restrictions: "Ribojimai",
    soil: "Dirvožemis",
    roads: "Keliai",
    weightsSum: "Svorių suma",
    weightDescriptions: {
      restrictions: "Natura 2000, miško dalis, valstybiniai miškai ir I-IV miškų grupės. Aukštesnė reikšmė reiškia mažiau ribojimų.",
      soil: "Dirvožemio tekstūra, pH, reljefas ir akmenuotumas. Aukštesnė reikšmė rodo palankesnes dirvožemio sąlygas.",
      road: "Skaičiuojamas pagal atstumą iki artimiausio valstybinio kelio. Kuo kelias arčiau, tuo aukštesnis kelių indeksas."
    },
    weightsNote: "Per didelė reikšmė automatiškai apribojama, kad bendra suma neviršytų 100. Langeliai su mažesne nei 20 % miško dalimi nerodomi.",
    top3: "Top 3 vietos",
    noTop3: "Šiuo metu nėra pakankamai duomenų.",
    rank: "vieta",
    index: "Indeksas",
    openOnMap: "Atidaryti žemėlapyje",
    pay: "Mokėti",
    processing: "Apdorojama...",
    paymentSystemLoading: "Mokėjimo sistema dar nėra pasiruošusi. Palaukite momentą.",
    stripeMissing: "Mokėjimo modulis nesukonfigūruotas. Susisiekite su administracija.",
    genericError: "Įvyko klaida. Bandykite dar kartą.",
    languageSelector: "Kalbos pasirinkimas",
    resetPasswordTitle: "Slaptažodžio atkūrimas",
    resetPasswordIntro: "Įveskite el. paštą, kad atsiųstume atkūrimo nuorodą.",
    resetPasswordSent: "Slaptažodžio atkūrimo nuoroda išsiųsta el. paštu.",
    sendResetLink: "Siųsti nuorodą",
    backToLogin: "Grįžti prisijungti",
    resetTokenInvalid: "Neteisingas arba pasenęs atkūrimo kodas.",
    resetTokenInvalidLong: "Neteisingas arba pasenęs slaptažodžio atkūrimo kodas.",
    tryAgain: "Bandyti dar kartą",
    errorTitle: "Klaida",
    newPasswordTitle: "Naujo slaptažodžio nustatymas",
    newPasswordIntro: "Įveskite naują slaptažodį.",
    newPassword: "Naujas slaptažodis",
    repeatNewPassword: "Pakartokite naują slaptažodį",
    repeatPassword: "Pakartokite slaptažodį",
    changePassword: "Keisti slaptažodį",
    passwordChanged: "Slaptažodis sėkmingai pakeistas. Galite prisijungti.",
    expiredCodeGeneric: "Įvyko klaida. Kodas gali būti pasenęs.",
    authInvalidToken: "Neteisingas prisijungimo tokenas.",
    authUserNotFound: "Naudotojas nerastas.",
    authEmailExists: "Naudotojas su šiuo el. pašto adresu jau egzistuoja.",
    authInvalidCredentials: "Neteisingas el. paštas arba slaptažodis.",
    authEmailNotFound: "El. paštas nerastas duomenų bazėje.",
    authResetLinkInvalid: "Nuoroda nebegalioja arba yra neteisinga.",
    fieldRequired: "Užpildykite privalomus laukus.",
    invalidRequest: "Patikrinkite įvestus duomenis ir bandykite dar kartą.",
  },
  en: {
    language: "EN",
    switchLanguage: "Lietuviškai",
    brandSubtitle: "Forestry analysis and investing",
    navMap: "Map",
    register: "Sign up",
    login: "Log in",
    logout: "Log out",
    home: "Home",
    goToMap: "Go to map",
    choose: "Choose",
    cancelPlan: "Cancel plan",
    cancelPlanTitle: "Cancel active plan?",
    cancelPlanText: "After cancelling, map access will stop until you buy another plan.",
    keepPlan: "Keep plan",
    confirmCancelPlan: "Yes, cancel",
    currentPlanFirst: "Cancel your current plan first",
    plan: "Plan",
    purchased: "Purchased",
    monthPeriod: "month",
    loginTitle: "Log in",
    loginIntro: "Log in to your account.",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    newAccount: "New account",
    invalidEmail: "Enter a valid email address.",
    passwordRequired: "Enter your password.",
    loginSuccess: "Logged in successfully.",
    accountCreated: "Account created successfully.",
    registerTitle: "Registration",
    registerIntro: "Create an account and start using the system.",
    name: "Name",
    firstName: "First name",
    lastName: "Last name",
    nameRequired: "Enter your name.",
    firstNameRequired: "Enter your first name.",
    lastNameRequired: "Enter your last name.",
    confirmPassword: "Confirm password",
    createAccount: "Create account",
    alreadyHaveAccount: "Already have an account?",
    passwordsDoNotMatch: "Passwords do not match.",
    strongPassword: "Password must be at least 8 characters and include an uppercase letter, a number, and a special character.",
    heroChip: "Forestry analytics and investing platform",
    heroSubtitle: "ForestForYou helps evaluate forest territories in Lithuania using geodata, infrastructure, soil indicators, and environmental restrictions. The system calculates an investment index and allows users to dynamically adjust evaluation weights according to their priorities.",
    heroNote: "Interactive mapping and spatial analysis help identify promising territories faster and provide a more objective way to compare different locations.",
    aboutProject: "About the project",
    aboutProjectText: "ForestForYou is a decision-support platform focused on forest territory evaluation and investment consulting processes. The system combines GIS analysis, geographic visualization, and a criteria-based evaluation model to support more efficient investment decisions. Instead of only displaying geographic data, the platform enables users to analyze territory suitability in real time based on their selected priorities.",
    choosePlan: "Choose a plan",
    teamMembers: "Team members",
    mentor: "Mentor",
    countyDayTitle: "One-day access for one county",
    countyDayDescription: "Short-term access to one county for reviewing data and assessing investment potential.",
    lithuaniaDayTitle: "One-day access for Lithuania",
    lithuaniaDayDescription: "One-day access to all Lithuanian objects for a quick market scan.",
    lithuaniaMonthTitle: "Monthly subscription for Lithuania",
    lithuaniaMonthDescription: "A subscription for regular work with Lithuania-wide data and priority territories.",
    selectedPlan: "Selected plan",
    payment: "Payment",
    paymentSuccess: "Payment successful. Access is active.",
    paymentRecordedError: "Payment succeeded, but access could not be recorded. Contact support.",
    paymentFailed: "Payment failed. Check the details and try again.",
    selectCounty: "Choose county",
    loadingCounties: "Loading county list...",
    backHome: "Back to home",
    alreadyPurchasedText: "You already have this plan. You can use the map.",
    activePlanBlocks: "You have another active plan. Cancel it before buying this one.",
    planCancelled: "Plan cancelled. You can now choose another plan.",
    mapAccessCheck: "Checking access...",
    mapLoading: "Loading map data...",
    status: "Status",
    dataReady: "Data is ready",
    dataLoadingShort: "Loading data extract...",
    objectCount: "Object count",
    legend: "Legend",
    excellent: "Highly suitable",
    good: "Suitable",
    average: "Moderate potential",
    bad: "Limited potential",
    veryBad: "Unsuitable",
    userWeights: "User weights",
    restrictions: "Restrictions",
    soil: "Soil",
    roads: "Roads",
    weightsSum: "Weights sum",
    weightDescriptions: {
      restrictions: "Natura 2000, forest share, state forests, and forest group I-IV coverage. Higher value means fewer restrictions.",
      soil: "Soil texture, pH, relief, and stoniness. Higher value means more favorable soil conditions.",
      road: "Calculated from the distance to the nearest national road. The closer the road, the higher the road index."
    },
    weightsNote: "Too large values are capped automatically so the total does not exceed 100. Cells with less than 20% forest coverage are hidden.",
    top3: "Top 3 places",
    noTop3: "There is not enough data right now.",
    rank: "place",
    index: "Index",
    openOnMap: "Open on map",
    pay: "Pay",
    processing: "Processing...",
    paymentSystemLoading: "The payment system is not ready yet. Please wait a moment.",
    stripeMissing: "The payment module is not configured. Contact support.",
    genericError: "Something went wrong. Try again.",
    languageSelector: "Language selection",
    resetPasswordTitle: "Password recovery",
    resetPasswordIntro: "Enter your email address and we will send you a recovery link.",
    resetPasswordSent: "Password recovery link has been sent to your email.",
    sendResetLink: "Send link",
    backToLogin: "Back to login",
    resetTokenInvalid: "The recovery code is invalid or expired.",
    resetTokenInvalidLong: "The password recovery code is invalid or expired.",
    tryAgain: "Try again",
    errorTitle: "Error",
    newPasswordTitle: "Set a new password",
    newPasswordIntro: "Enter a new password.",
    newPassword: "New password",
    repeatNewPassword: "Repeat new password",
    repeatPassword: "Repeat password",
    changePassword: "Change password",
    passwordChanged: "Password changed successfully. You can log in.",
    expiredCodeGeneric: "Something went wrong. The code may be expired.",
    authInvalidToken: "Invalid login token.",
    authUserNotFound: "User not found.",
    authEmailExists: "A user with this email address already exists.",
    authInvalidCredentials: "Invalid email or password.",
    authEmailNotFound: "Email was not found in the database.",
    authResetLinkInvalid: "The link is expired or invalid.",
    fieldRequired: "Fill in the required fields.",
    invalidRequest: "Check the entered details and try again.",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("language") || "lt");

  const value = useMemo(() => {
    const setAppLanguage = (nextLanguage) => {
      localStorage.setItem("language", nextLanguage);
      setLanguage(nextLanguage);
    };

    return {
      language,
      setLanguage: setAppLanguage,
      toggleLanguage: () => setAppLanguage(language === "lt" ? "en" : "lt"),
      t: (key) => translations[language]?.[key] || translations.lt[key] || key,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
