/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  lt: {
    language: "LT",
    switchLanguage: "English",
    brandSubtitle: "Miškininkystės analizė ir investavimas",
    navMap: "Žemėlapis",
    register: "Registruotis",
    login: "Prisijungti",
    logout: "Atsijungti",
    home: "Pagrindinis",
    goToMap: "Eiti į žemėlapį",
    choose: "Pasirinkti",
    cancelPlan: "Atšaukti planą",
    cancelPlanTitle: "Atšaukti aktyvų planą?",
    cancelPlanText: "Atšaukus planą prieiga prie žemėlapio bus sustabdyta, kol įsigysite kitą planą.",
    keepPlan: "Palikti planą",
    confirmCancelPlan: "Taip, atšaukti",
    currentPlanFirst: "Pirma atšaukite dabartinį planą",
    plan: "Planas",
    purchased: "Įsigyta",
    monthPeriod: "mėn.",
    loginTitle: "Prisijungimas",
    loginIntro: "Prisijunkite prie paskyros.",
    email: "El. paštas",
    password: "Slaptažodis",
    forgotPassword: "Pamiršote slaptažodį?",
    newAccount: "Nauja paskyra",
    invalidEmail: "Įveskite korektišką el. pašto adresą.",
    passwordRequired: "Įveskite slaptažodį.",
    loginSuccess: "Prisijungta sėkmingai.",
    registerTitle: "Registracija",
    registerIntro: "Sukurkite paskyrą ir pradėkite naudotis sistema.",
    name: "Vardas",
    confirmPassword: "Patvirtinkite slaptažodį",
    createAccount: "Kurti paskyrą",
    alreadyHaveAccount: "Jau turite paskyrą?",
    passwordsDoNotMatch: "Slaptažodžiai nesutampa.",
    strongPassword: "Slaptažodis turi būti bent 8 simbolių, turėti didžiąją raidę, skaičių ir specialų simbolį.",
    heroChip: "Miškininkystės analizės ir investavimo platforma",
    heroSubtitle: "Interaktyvi sistema miško teritorijų vertinimui pagal geoduomenis, ribojimus, dirvožemio savybes ir susisiekimą.",
    heroNote: "Sistema padeda greičiau susiaurinti paiešką ir pamatyti prioritetines teritorijas žemėlapyje.",
    aboutProject: "Apie projektą",
    aboutProjectText: "ForestForYou yra SaaS tipo miškininkystės analizės platforma, skirta aiškesniam teritorijų vertinimui ir investavimo sprendimų palaikymui.",
    choosePlan: "Pasirinkite planą",
    teamMembers: "Komandos nariai",
    mentor: "Mentorius",
    countyDayTitle: "Vienos dienos prieiga vienai apskričiai",
    countyDayDescription: "Trumpalaikė prieiga konkrečios apskrities duomenų peržiūrai ir investicinio potencialo įvertinimui.",
    lithuaniaDayTitle: "Vienos dienos prieiga visai Lietuvai",
    lithuaniaDayDescription: "Vienos dienos prieiga visos Lietuvos objektų peržiūrai, skirta greitam rinkos įvertinimui.",
    lithuaniaMonthTitle: "Mėnesio prenumerata visai Lietuvai",
    lithuaniaMonthDescription: "Prenumerata reguliariam darbui su visos Lietuvos duomenimis ir prioritetinėmis teritorijomis.",
    selectedPlan: "Pasirinktas planas",
    payment: "Mokėjimas",
    paymentSuccess: "Mokėjimas sėkmingas. Prieiga aktyvuota.",
    paymentRecordedError: "Mokėjimas atliktas, bet prieigos įrašyti nepavyko. Susisiekite su administracija.",
    paymentFailed: "Mokėjimas nepavyko. Patikrinkite duomenis ir bandykite dar kartą.",
    selectCounty: "Pasirinkite apskritį",
    loadingCounties: "Kraunamas apskričių sąrašas...",
    backHome: "Grįžti į pradinį puslapį",
    alreadyPurchasedText: "Jūs jau turite šį planą. Galite naudotis žemėlapiu.",
    activePlanBlocks: "Turite aktyvų kitą planą. Norėdami įsigyti šį, pirmiausia atšaukite dabartinį planą.",
    planCancelled: "Planas atšauktas. Dabar galite rinktis kitą planą.",
    mapAccessCheck: "Tikrinama prieiga...",
    mapLoading: "Kraunami žemėlapio duomenys...",
    status: "Būsena",
    dataReady: "Duomenys paruošti peržiūrai",
    dataLoadingShort: "Kraunama duomenų ištrauka...",
    objectCount: "Objektų kiekis",
    legend: "Legenda",
    excellent: "Puiku",
    good: "Gerai",
    average: "Vidutiniškai",
    bad: "Blogai",
    veryBad: "Labai blogai",
    userWeights: "Naudotojo svoriai",
    restrictions: "Ribojimai",
    soil: "Dirvožemis",
    roads: "Keliai",
    weightsSum: "Svorių suma",
    weightsNote: "Per didelė reikšmė automatiškai apribojama, kad bendra suma neviršytų 100. Celės su mažesne nei 20 % miško dalimi nerodomos.",
    top3: "Top 3 vietos",
    noTop3: "Šiuo metu nėra pakankamai duomenų.",
    rank: "vieta",
    index: "Indeksas",
    openOnMap: "Atidaryti žemėlapyje",
    pay: "Mokėti",
    processing: "Apdorojama...",
    paymentSystemLoading: "Mokėjimo sistema dar nėra pasiruošusi. Palaukite momentą.",
    stripeMissing: "Mokėjimo modulis nesukonfigūruotas. Susisiekite su administracija.",
    genericError: "Įvyko klaida. Bandykite dar kartą.",
  },
  en: {
    language: "EN",
    switchLanguage: "Lietuviškai",
    brandSubtitle: "Forestry analysis and investing",
    navMap: "Map",
    register: "Sign up",
    login: "Log in",
    logout: "Log out",
    home: "Home",
    goToMap: "Go to map",
    choose: "Choose",
    cancelPlan: "Cancel plan",
    cancelPlanTitle: "Cancel active plan?",
    cancelPlanText: "After cancelling, map access will stop until you buy another plan.",
    keepPlan: "Keep plan",
    confirmCancelPlan: "Yes, cancel",
    currentPlanFirst: "Cancel your current plan first",
    plan: "Plan",
    purchased: "Purchased",
    monthPeriod: "month",
    loginTitle: "Log in",
    loginIntro: "Log in to your account.",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    newAccount: "New account",
    invalidEmail: "Enter a valid email address.",
    passwordRequired: "Enter your password.",
    loginSuccess: "Logged in successfully.",
    registerTitle: "Registration",
    registerIntro: "Create an account and start using the system.",
    name: "Name",
    confirmPassword: "Confirm password",
    createAccount: "Create account",
    alreadyHaveAccount: "Already have an account?",
    passwordsDoNotMatch: "Passwords do not match.",
    strongPassword: "Password must be at least 8 characters and include an uppercase letter, a number, and a special character.",
    heroChip: "Forestry analytics and investing platform",
    heroSubtitle: "An interactive system for evaluating forest areas using geodata, restrictions, soil characteristics, and access roads.",
    heroNote: "The system helps narrow the search faster and highlight priority areas on the map.",
    aboutProject: "About the project",
    aboutProjectText: "ForestForYou is a SaaS forestry analytics platform built for clearer territory evaluation and investment decision support.",
    choosePlan: "Choose a plan",
    teamMembers: "Team members",
    mentor: "Mentor",
    countyDayTitle: "One-day access for one county",
    countyDayDescription: "Short-term access to one county for reviewing data and assessing investment potential.",
    lithuaniaDayTitle: "One-day access for Lithuania",
    lithuaniaDayDescription: "One-day access to all Lithuanian objects for a quick market scan.",
    lithuaniaMonthTitle: "Monthly subscription for Lithuania",
    lithuaniaMonthDescription: "A subscription for regular work with Lithuania-wide data and priority territories.",
    selectedPlan: "Selected plan",
    payment: "Payment",
    paymentSuccess: "Payment successful. Access is active.",
    paymentRecordedError: "Payment succeeded, but access could not be recorded. Contact support.",
    paymentFailed: "Payment failed. Check the details and try again.",
    selectCounty: "Choose county",
    loadingCounties: "Loading county list...",
    backHome: "Back to home",
    alreadyPurchasedText: "You already have this plan. You can use the map.",
    activePlanBlocks: "You have another active plan. Cancel it before buying this one.",
    planCancelled: "Plan cancelled. You can now choose another plan.",
    mapAccessCheck: "Checking access...",
    mapLoading: "Loading map data...",
    status: "Status",
    dataReady: "Data is ready",
    dataLoadingShort: "Loading data extract...",
    objectCount: "Object count",
    legend: "Legend",
    excellent: "Excellent",
    good: "Good",
    average: "Average",
    bad: "Bad",
    veryBad: "Very bad",
    userWeights: "User weights",
    restrictions: "Restrictions",
    soil: "Soil",
    roads: "Roads",
    weightsSum: "Weights sum",
    weightsNote: "Too large values are capped automatically so the total does not exceed 100. Cells with less than 20% forest coverage are hidden.",
    top3: "Top 3 places",
    noTop3: "There is not enough data right now.",
    rank: "place",
    index: "Index",
    openOnMap: "Open on map",
    pay: "Pay",
    processing: "Processing...",
    paymentSystemLoading: "The payment system is not ready yet. Please wait a moment.",
    stripeMissing: "The payment module is not configured. Contact support.",
    genericError: "Something went wrong. Try again.",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("language") || "lt");

  const value = useMemo(() => {
    const setAppLanguage = (nextLanguage) => {
      localStorage.setItem("language", nextLanguage);
      setLanguage(nextLanguage);
    };

    return {
      language,
      setLanguage: setAppLanguage,
      toggleLanguage: () => setAppLanguage(language === "lt" ? "en" : "lt"),
      t: (key) => translations[language]?.[key] || translations.lt[key] || key,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
